# Generated by Django 4.2 on 2023-04-25 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('photo', models.ImageField(blank=True, upload_to='content/images/%Y%m%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Музыкальный исполнитель',
                'verbose_name_plural': 'Музыкальные исполнители',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_name', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(default='Релиз', max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank='false', default='', max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='content/album_images/%Y%m%d/')),
                ('category_by_artists', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='northern_label.artists')),
            ],
            options={
                'verbose_name': 'Релиз',
                'verbose_name_plural': 'Релизы',
            },
        ),
    ]
